
DROP TABLE IF EXISTS  CATALOGO;
DROP TABLE IF EXISTS  CAMBIO_MONEDA;



  CREATE TABLE CATALOGO 
   (	
    ID bigint auto_increment,
    GRUPO VARCHAR2(100),
    NOMBRE VARCHAR2(100),
    CODIGO VARCHAR2(100),
    ESTADO INT(1)	
   ) ;
--------------------------------------------------------
--  DDL for Table BNGJF05_LOG_SISTEMA
--------------------------------------------------------

  CREATE TABLE CAMBIO_MONEDA 
   (
    ID bigint auto_increment,
    CODIGO_MONEDA VARCHAR2(50), 
	CODIGO_CAMBIO VARCHAR2(100),
	VALOR DECIMAL(20,4), 
	FECHA_ACTUALIZACION DATETIME 
   );
   
   INSERT INTO CATALOGO (GRUPO,NOMBRE,CODIGO,ESTADO) VALUES ('MONEDA','SOLES','PEN',1);
   INSERT INTO CATALOGO (GRUPO,NOMBRE,CODIGO,ESTADO) VALUES ('MONEDA','DOLARES','USD',1);
   INSERT INTO CATALOGO (GRUPO,NOMBRE,CODIGO,ESTADO) VALUES ('TIPO_CAMBIO','COMPRA','COMPRA',1);
   INSERT INTO CATALOGO (GRUPO,NOMBRE,CODIGO,ESTADO) VALUES ('TIPO_CAMBIO','VENTA','VENTA',1);

   INSERT INTO CAMBIO_MONEDA (CODIGO_MONEDA,CODIGO_CAMBIO,VALOR,FECHA_ACTUALIZACION) VALUES ('USD','COMPRA',3.5635,CURRENT_TIMESTAMP);
INSERT INTO CAMBIO_MONEDA (CODIGO_MONEDA,CODIGO_CAMBIO,VALOR,FECHA_ACTUALIZACION) VALUES ('USD','VENTA',3.5905,CURRENT_TIMESTAMP);
